# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfDMqQs6fxJJ7bUfuDw6q-M8HIch61Sl
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect to SQLite database
db_connection = sqlite3.connect("sales_data.db")
db_cursor = db_connection.cursor()

# Create a table for storing sales records
db_cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT NOT NULL,
    units_sold INTEGER NOT NULL,
    unit_price REAL NOT NULL
)
""")

# Insert some sample data
sales_entries = [
    ('Laptop', 3, 55000.0),
    ('Headphones', 10, 1500.0),
    ('Laptop', 2, 55000.0),
    ('Wireless Mouse', 15, 800.0),
    ('Headphones', 5, 1500.0)
]

# Match the correct column names if you changed them earlier
db_cursor.executemany(
    "INSERT INTO sales (product_name, units_sold, unit_price) VALUES (?, ?, ?)",
    sales_entries
)

# Commit the changes
db_connection.commit()

# Run SQL query to get total quantity and revenue per product
query = """
SELECT
    product_name,
    SUM(units_sold) AS total_qty,
    SUM(units_sold * unit_price ) AS revenue
FROM sales
GROUP BY product_name
"""
df = pd.read_sql_query(query, db_connection)

# Display results
print("Sales Summary:")
print(df)

# Plot bar chart (Revenue per Product)
df.plot(kind='bar', x='product_name', y='revenue', legend=False)
plt.title('Revenue by Product')
plt.ylabel('Revenue')
plt.tight_layout()
plt.savefig("sales_chart.png")  # Optional: Save chart
plt.show()

# Close the database connection
db_connection.close()